In [1]:
%pip install openpyxl

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
import os
import pandas as pd

# Verificar os arquivos disponíveis no JupyterLite
print(os.listdir())

['FeminicidiosGoias_analise.ipynb', 'Untitled3.ipynb', 'r.ipynb', 'Lorenz.ipynb', 'Mandelbrot.ipynb', 'sqlite.ipynb', 'cpp.ipynb', 'cpp-third-party-libs.ipynb', 'cpp-tiny-ray-tracer.ipynb', 'Intro.ipynb']

In [10]:
df = pd.read_excel("feminicidios2025.xlsx")
df.head(4)

,Identificador,Fonte,Dia,Mês,Ano,Estado,Município,Código do município,Local do crime,Idade da vítima,Vínculo entre vítima e suspeito,Arma ou meio utilizado,Filhos dependentes (informação disponível?),Consumado ou Tentado,Idade do agressor,Período do dia
0,2025-BR-0004,Imprensa,1.0,1,2025,Minas Gerais,tres marias,3169356,Residência do casal,41.0,Parceiro/coabitante/vínculo sexual emocional,Arma de fogo,Sim,Consumado,49.0,Noite
1,2025-BR-0005,Imprensa,1.0,1,2025,Minas Gerais,tres marias,3169356,Residência do casal,13.0,Membro da família por afiliação,Arma de fogo,Não,Consumado,49.0,Noite
2,2025-BR-0006,Imprensa,1.0,1,2025,Rondônia,porto velho,1100205,Outra habitação,39.0,Parceiro/coabitante/vínculo sexual emocional,Arma branca,Incerto/Desconhecido,Consumado,44.0,Incerto/Desconhecido
3,2025-BR-0007,Imprensa,1.0,1,2025,Santa Catarina,palhoca,4211900,Incerto/Desconhecido,19.0,Parceiro/coabitante/vínculo sexual emocional,Arma branca,Não,Consumado,33.0,Noite

In [11]:
print("linhas e colunas:", df.shape)

linhas e colunas: (2149, 16)

In [12]:
print("tipos de dados:", df.dtypes)

tipos de dados: Identificador                                      str
Fonte                                              str
Dia                                            float64
Mês                                              int64
Ano                                              int64
Estado                                             str
Município                                          str
Código do município                              int64
Local do crime                                     str
Idade da vítima                                float64
Vínculo entre vítima e suspeito                    str
Arma ou meio utilizado                             str
Filhos dependentes (informação disponível?)        str
Consumado ou Tentado                               str
Idade do agressor                              float64
Período do dia                                     str
dtype: object

In [13]:
print("valores ausentes: ")
print(df.isnull().sum())

valores ausentes:
Identificador                                     0
Fonte                                             0
Dia                                             345
Mês                                               0
Ano                                               0
Estado                                            0
Município                                         0
Código do município                               0
Local do crime                                    0
Idade da vítima                                 527
Vínculo entre vítima e suspeito                   0
Arma ou meio utilizado                            0
Filhos dependentes (informação disponível?)       0
Consumado ou Tentado                              0
Idade do agressor                              1123
Período do dia                                    0
dtype: int64

In [14]:
print("valores duplicados")
print(df.duplicated().sum())

valores duplicados
0

In [18]:
df = df.drop(columns=["Filhos dependentes (informação disponível?)", "Consumado ou Tentado"])
df.head(4)

,Dia,Mês,Ano,Estado,Município,Local do crime,Idade da vítima,Vínculo entre vítima e suspeito,Arma ou meio utilizado,Idade do agressor,Período do dia
0,1.0,1,2025,Minas Gerais,tres marias,Residência do casal,41.0,Parceiro/coabitante/vínculo sexual emocional,Arma de fogo,49.0,Noite
1,1.0,1,2025,Minas Gerais,tres marias,Residência do casal,13.0,Membro da família por afiliação,Arma de fogo,49.0,Noite
2,1.0,1,2025,Rondônia,porto velho,Outra habitação,39.0,Parceiro/coabitante/vínculo sexual emocional,Arma branca,44.0,Incerto/Desconhecido
3,1.0,1,2025,Santa Catarina,palhoca,Incerto/Desconhecido,19.0,Parceiro/coabitante/vínculo sexual emocional,Arma branca,33.0,Noite

In [19]:
df['Idade da vítima'] = df['Idade da vítima'].astype('Int64')
df['Idade do agressor'] = df['Idade do agressor'].astype('Int64')
df.head(5)

,Dia,Mês,Ano,Estado,Município,Local do crime,Idade da vítima,Vínculo entre vítima e suspeito,Arma ou meio utilizado,Idade do agressor,Período do dia
0,1.0,1,2025,Minas Gerais,tres marias,Residência do casal,41,Parceiro/coabitante/vínculo sexual emocional,Arma de fogo,49,Noite
1,1.0,1,2025,Minas Gerais,tres marias,Residência do casal,13,Membro da família por afiliação,Arma de fogo,49,Noite
2,1.0,1,2025,Rondônia,porto velho,Outra habitação,39,Parceiro/coabitante/vínculo sexual emocional,Arma branca,44,Incerto/Desconhecido
3,1.0,1,2025,Santa Catarina,palhoca,Incerto/Desconhecido,19,Parceiro/coabitante/vínculo sexual emocional,Arma branca,33,Noite
4,1.0,1,2025,São Paulo,sao paulo,Residência do casal,39,Parceiro/coabitante/vínculo sexual emocional,Objetos contundentes,38,Noite